### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [10]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[191, 124, 191, 4], [191, 124, 191, 201], [191, 337, 191, 71], [329, 101, 499, 4, 140], [329, 101, 499, 4, 104], [79, 191, 402, 191, 261], [326, 312, 261, 4]]


All the sentences are of different size , if i want to train this in neural network then all the sentences size should be same that is the reason we do post and pre padding.

Here max_size of sentence is 5

### Word Embedding Represntation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
## pre padding  -- for all the sentences it will make sure size would be 8 by adding 0 to last or at first
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 191 124 191   4]
 [  0   0   0   0 191 124 191 201]
 [  0   0   0   0 191 337 191  71]
 [  0   0   0 329 101 499   4 140]
 [  0   0   0 329 101 499   4 104]
 [  0   0   0  79 191 402 191 261]
 [  0   0   0   0 326 312 261   4]]


Now we will convert each and every value with vectors

In [14]:
## 10 feature dimesnions -- here we are representing each value with 10 dimension
dim=10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))  ##vocabulary_size, feature dimension, length of sentence
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 191, 124, 191,   4], dtype=int32)

In [18]:
model.predict(embedded_docs[0])   ##here each value is represented by 10 dimension.

1/1 [==============================] - 0s 124ms/step


array([[ 0.00643486, -0.00214151, -0.01206472,  0.03227807, -0.009312  ,
        -0.04557151, -0.03118416, -0.00619029,  0.02124581, -0.03742839],
       [ 0.00643486, -0.00214151, -0.01206472,  0.03227807, -0.009312  ,
        -0.04557151, -0.03118416, -0.00619029,  0.02124581, -0.03742839],
       [ 0.00643486, -0.00214151, -0.01206472,  0.03227807, -0.009312  ,
        -0.04557151, -0.03118416, -0.00619029,  0.02124581, -0.03742839],
       [ 0.00643486, -0.00214151, -0.01206472,  0.03227807, -0.009312  ,
        -0.04557151, -0.03118416, -0.00619029,  0.02124581, -0.03742839],
       [-0.00935941,  0.01799064,  0.00527639,  0.0346641 ,  0.02105578,
        -0.03100882,  0.03641781, -0.02179631, -0.04746579, -0.01452301],
       [-0.01288809, -0.04284729,  0.0495101 ,  0.01706329,  0.04278364,
        -0.04172645,  0.03532929,  0.02405829, -0.00374184,  0.03239402],
       [-0.00935941,  0.01799064,  0.00527639,  0.0346641 ,  0.02105578,
        -0.03100882,  0.03641781, -0.02179631

In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[ 0.00643486 -0.00214151 -0.01206472  0.03227807 -0.009312
   -0.04557151 -0.03118416 -0.00619029  0.02124581 -0.03742839]
  [ 0.00643486 -0.00214151 -0.01206472  0.03227807 -0.009312
   -0.04557151 -0.03118416 -0.00619029  0.02124581 -0.03742839]
  [ 0.00643486 -0.00214151 -0.01206472  0.03227807 -0.009312
   -0.04557151 -0.03118416 -0.00619029  0.02124581 -0.03742839]
  [ 0.00643486 -0.00214151 -0.01206472  0.03227807 -0.009312
   -0.04557151 -0.03118416 -0.00619029  0.02124581 -0.03742839]
  [-0.00935941  0.01799064  0.00527639  0.0346641   0.02105578
   -0.03100882  0.03641781 -0.02179631 -0.04746579 -0.01452301]
  [-0.01288809 -0.04284729  0.0495101   0.01706329  0.04278364
   -0.04172645  0.03532929  0.02405829 -0.00374184  0.03239402]
  [-0.00935941  0.01799064  0.00527639  0.0346641   0.02105578
   -0.03100882  0.03641781 -0.02179631 -0.04746579 -0.01452301]
  [-0.02666402  0.03251394  0.03274452  0.01276537 -0.01673452
    

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]

In [20]:
### Next task

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
## Setting vocabulary_size

vocab_size = 1000

In [21]:
## Applying one hot encoding

onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)


[[191, 439, 142, 499, 316, 12], [210, 173, 142, 336, 133, 416], [329, 432, 297, 288], [191, 453, 142, 25, 191, 105], [482, 490, 82, 142, 336, 133, 416], [333, 142, 336, 133, 409, 471]]


In [23]:
## Word Embedding Representation
sent_length=9
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 191 439 142 499 316  12]
 [  0   0   0 210 173 142 336 133 416]
 [  0   0   0   0   0 329 432 297 288]
 [  0   0   0 191 453 142  25 191 105]
 [  0   0 482 490  82 142 336 133 416]
 [  0   0   0 333 142 336 133 409 471]]


In [24]:
## Setting feature dimension

dim = 10

In [25]:
## Model Training
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))  ##vocabulary_size, feature dimension, length of sentence
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 9, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
embedded_docs[0]

array([  0,   0,   0, 191, 439, 142, 499, 316,  12], dtype=int32)

In [27]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[ 0.00492467, -0.02851629,  0.03155783, -0.00936496, -0.02822329,
        -0.01547574,  0.04704932,  0.00253701, -0.04282079,  0.02278955],
       [ 0.00492467, -0.02851629,  0.03155783, -0.00936496, -0.02822329,
        -0.01547574,  0.04704932,  0.00253701, -0.04282079,  0.02278955],
       [ 0.00492467, -0.02851629,  0.03155783, -0.00936496, -0.02822329,
        -0.01547574,  0.04704932,  0.00253701, -0.04282079,  0.02278955],
       [ 0.0162755 , -0.02363986, -0.01885958,  0.04726828,  0.02552284,
         0.02030608,  0.00116736,  0.02343532,  0.03802613,  0.02589131],
       [-0.04256337,  0.01450396,  0.04595615, -0.00795612, -0.02332662,
        -0.00314047, -0.00302789,  0.03091553, -0.00094907, -0.03142238],
       [-0.026124  , -0.01892481, -0.03268179,  0.01164757, -0.01292402,
         0.04024089, -0.01298885,  0.01368585,  0.00811225,  0.00269381],
       [ 0.04466968, -0.00994332,  0.00486178, -0.0384124 ,  0.01510962,
         0.0046116 , -0.03489342,  0.00384557

In [29]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 37ms/step


array([[[ 0.00492467, -0.02851629,  0.03155783, -0.00936496,
         -0.02822329, -0.01547574,  0.04704932,  0.00253701,
         -0.04282079,  0.02278955],
        [ 0.00492467, -0.02851629,  0.03155783, -0.00936496,
         -0.02822329, -0.01547574,  0.04704932,  0.00253701,
         -0.04282079,  0.02278955],
        [ 0.00492467, -0.02851629,  0.03155783, -0.00936496,
         -0.02822329, -0.01547574,  0.04704932,  0.00253701,
         -0.04282079,  0.02278955],
        [ 0.0162755 , -0.02363986, -0.01885958,  0.04726828,
          0.02552284,  0.02030608,  0.00116736,  0.02343532,
          0.03802613,  0.02589131],
        [-0.04256337,  0.01450396,  0.04595615, -0.00795612,
         -0.02332662, -0.00314047, -0.00302789,  0.03091553,
         -0.00094907, -0.03142238],
        [-0.026124  , -0.01892481, -0.03268179,  0.01164757,
         -0.01292402,  0.04024089, -0.01298885,  0.01368585,
          0.00811225,  0.00269381],
        [ 0.04466968, -0.00994332,  0.00486178, -0.0